# Site settings
title: Victor Gil - Web Developer
email: victorgb6@gmail.com
description: "Victor Gil Borrego front end web developer."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Victor Gil Borrego
  location: Location
  social: Around the Web
  credits: Download my Resumé

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/victorgb6
  - title: linkedin
    url: http://es.linkedin.com/in/victorgilborrego/es
  - title: github
    url: http://github.com/victorgb6

# Languages Skills (Level between 0 and 5)
skillslist:
  - headtitle: Languages
    skillset:
    - title: HTML
      level: 5
    - title: CSS(SASS)
      level: 5
    - title: Javascript
      level: 5
    - title: Angular
      level: 4
    - title: Polymer
      level: 3
    - title: React
      level: 3
    - title: Node.js
      level: 3
  - headtitle: Software
    skillset:
    - title: Adobe Photoshop
      level: 4
    - title: Sketch
      level: 3
    - title: Grunt
      level: 4
    - title: Gulp
      level: 4
    - title: Mongodb
      level: 3
    - title: Firebase
      level: 3
    - title: TDD/End to end testing
      level: 4

  - headtitle: Spoken
    skillset:
    - title: Spanish
      level: 5
    - title: English
      level: 4
  - headtitle: Other Skills
    skillset:
    - title: Responsive Design
      level: 5
    - title: User Experience
      level: 3
    - title: Wordpress
      level: 4
    - title: Progressive Web Apps
      level: 5
    - title: Mean Stack
      level: 4

# Employment Items
employments:
  - title: Front End Developer at NexusIT / DigitasLBi Madrid
    time: Apr 2015 - Present
    description: 'I am working as a Front End Developer at NexusIT/DigitasLBi Spain, working in different projects using technologies like Angular, Sass, etc. ensuring the quality of the code and best practices.'
  - title: Front End Developer and UI Designer at Telecoming Madrid
    time: Oct 2013 - Apr 2015
    description: 'I am currently working at Telecoming and more specifically on the Virtual Center 360 project, which is an online platform where companies can manage all their communications in one place, with special attention to the customer care service. I am responsible for the front end part of the platform, including all the javascript code, and the HTML and CSS aswell.'
  - title: Internship as Front End Developer at KS-Agency London
    time: Mar 2013 - Jun 2013
    description: 'I was an intern for KS Agency, a small marketing agency in the Soho area of London. I was helping them with a couple of projects during about three months and a half. My duties were to convert PSD designs into HTML and CSS, and do some Javascript work too.'
# Postal address (add as many lines as necessary)
address:
  - line: 'Madrid, Spain'

# Credits content
credits: '<a href="/portfolio2/Victor_Gil_2015.pdf">Click here to download</a>'

# Build settings
markdown: kramdown
permalink: pretty
baseurl: /portfolio2
